 Inverse of a rotation matrix

In [1]:
import numpy as np

def inverse_rotation_matrix(R):
    return np.transpose(R)

R = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
R_inv = inverse_rotation_matrix(R)
print("Inverse of Rotation Matrix R:\n", R_inv)


Inverse of Rotation Matrix R:
 [[ 1  0  0]
 [ 0  0  1]
 [ 0 -1  0]]


Skew-symmetric matrix from a 3-vector

In [2]:
def skew_symmetric_matrix(omega):
    return np.array([[0, -omega[2], omega[1]],
                     [omega[2], 0, -omega[0]],
                     [-omega[1], omega[0], 0]])


omega = np.array([1, 2, 3])
skew_matrix = skew_symmetric_matrix(omega)
print("Skew-symmetric matrix:\n", skew_matrix)


Skew-symmetric matrix:
 [[ 0 -3  2]
 [ 3  0 -1]
 [-2  1  0]]


Rodrigues' rotation formula

In [3]:
def rodrigues_rotation_formula(omega, theta):
    omega = omega / np.linalg.norm(omega)
    omega_skew = skew_symmetric_matrix(omega)
    I = np.eye(3)
    return I + np.sin(theta) * omega_skew + (1 - np.cos(theta)) * np.dot(omega_skew, omega_skew)


omega = np.array([0, 0, 1])
theta = np.pi / 4
R = rodrigues_rotation_formula(omega, theta)
print("Rotation matrix using Rodrigues' formula:\n", R)


Rotation matrix using Rodrigues' formula:
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


3 × 3 skew-symmetric matrix to 3-vector

In [4]:
def vector_from_skew_symmetric(skew_matrix):
    return np.array([skew_matrix[2, 1], skew_matrix[0, 2], skew_matrix[1, 0]])


skew_matrix = np.array([[0, -3, 2], [3, 0, -1], [-2, 1, 0]])
omega = vector_from_skew_symmetric(skew_matrix)
print("Recovered 3-vector from skew-symmetric matrix:", omega)


Recovered 3-vector from skew-symmetric matrix: [1 2 3]


Extract rotation axis and angle from exponential coordinates

In [5]:
def extract_rotation_axis_angle(omega_theta):
    theta = np.linalg.norm(omega_theta)
    omega = omega_theta / theta
    return omega, theta


omega_theta = np.array([1, 1, 0])
omega, theta = extract_rotation_axis_angle(omega_theta)
print("Rotation axis:", omega)
print("Rotation angle:", theta)


Rotation axis: [0.70710678 0.70710678 0.        ]
Rotation angle: 1.4142135623730951


Rotation matrix to axis and angle

In [6]:
def rotation_matrix_to_axis_angle(R):
    theta = np.arccos((np.trace(R) - 1) / 2)
    omega_skew = (R - R.T) / (2 * np.sin(theta))
    omega = vector_from_skew_symmetric(omega_skew)
    return omega, theta


R = np.array([[0.7071, -0.7071, 0],
              [0.7071, 0.7071, 0],
              [0, 0, 1]])
omega, theta = rotation_matrix_to_axis_angle(R)
print("Rotation axis:", omega)
print("Rotation angle:", theta)


Rotation axis: [0.         0.         0.99998082]
Rotation angle: 0.7854077533974488


Homogeneous matrix from rotation matrix and position vector

In [7]:
def homogeneous_matrix(R, p):
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = p
    return T

R = np.eye(3)
p = np.array([1, 2, 3])
T = homogeneous_matrix(R, p)
print("Homogeneous transformation matrix:\n", T)


Homogeneous transformation matrix:
 [[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]


Extract rotation matrix and position vector from homogeneous matrix

In [8]:
def extract_from_homogeneous_matrix(T):
    R = T[:3, :3]
    p = T[:3, 3]
    return R, p

T = np.array([[1, 0, 0, 1],
              [0, 1, 0, 2],
              [0, 0, 1, 3],
              [0, 0, 0, 1]])
R, p = extract_from_homogeneous_matrix(T)
print("Rotation matrix R:\n", R)
print("Position vector p:", p)


Rotation matrix R:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Position vector p: [1 2 3]


Inverse of homogeneous transformation matrix

In [9]:
def inverse_homogeneous_matrix(T):
    R = T[:3, :3]
    p = T[:3, 3]
    T_inv = np.eye(4)
    T_inv[:3, :3] = R.T
    T_inv[:3, 3] = -np.dot(R.T, p)
    return T_inv

T = np.array([[1, 0, 0, 1],
              [0, 1, 0, 2],
              [0, 0, 1, 3],
              [0, 0, 0, 1]])
T_inv = inverse_homogeneous_matrix(T)
print("Inverse of Homogeneous Matrix:\n", T_inv)


Inverse of Homogeneous Matrix:
 [[ 1.  0.  0. -1.]
 [ 0.  1.  0. -2.]
 [ 0.  0.  1. -3.]
 [ 0.  0.  0.  1.]]


Homogeneous coordinates of a 3-vector

In [10]:
def homogeneous_coordinates(vector):
    return np.append(vector, 1)


vector = np.array([1, 2, 3])
homogeneous_vec = homogeneous_coordinates(vector)
print("Homogeneous coordinates of vector:", homogeneous_vec)


Homogeneous coordinates of vector: [1 2 3 1]


Adjoint representation of homogeneous transformation matrix

In [11]:
def adjoint_representation(T):
    R, p = extract_from_homogeneous_matrix(T)
    p_skew = skew_symmetric_matrix(p)
    adj_T = np.zeros((6, 6))
    adj_T[:3, :3] = R
    adj_T[3:, 3:] = R
    adj_T[3:, :3] = np.dot(p_skew, R)
    return adj_T

T = np.array([[1, 0, 0, 1],
              [0, 1, 0, 2],
              [0, 0, 1, 3],
              [0, 0, 0, 1]])
adj_T = adjoint_representation(T)
print("Adjoint representation:\n", adj_T)


Adjoint representation:
 [[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0. -3.  2.  1.  0.  0.]
 [ 3.  0. -1.  0.  1.  0.]
 [-2.  1.  0.  0.  0.  1.]]


Extract normalized screw axis and distance from exponential coordinates of motion

In [13]:
def extract_screw_axis_distance(Sq):
    q = np.linalg.norm(Sq[:3])
    S = Sq / q
    return S, q


Sq = np.array([1, 0, 0, 0, 1, 2])
S, q = extract_screw_axis_distance(Sq)
print("Screw axis S:", S)
print("Distance q:", q)


Screw axis S: [1. 0. 0. 0. 1. 2.]
Distance q: 1.0


Matrix representation of screw axis

In [14]:
def screw_axis_to_matrix(S):
    omega = S[:3]
    v = S[3:]
    omega_skew = skew_symmetric_matrix(omega)
    S_matrix = np.zeros((4, 4))
    S_matrix[:3, :3] = omega_skew
    S_matrix[:3, 3] = v
    return S_matrix


S = np.array([0, 0, 1, 1, 2, 3])
S_matrix = screw_axis_to_matrix(S)
print("Matrix representation of screw axis:\n", S_matrix)


Matrix representation of screw axis:
 [[ 0. -1.  0.  1.]
 [ 1.  0.  0.  2.]
 [ 0.  0.  0.  3.]
 [ 0.  0.  0.  0.]]


 Homogeneous transformation matrix from screw axis and distance

In [15]:
def homogeneous_transformation_from_screw(S, q):
    omega = S[:3]
    v = S[3:]
    R = rodrigues_rotation_formula(omega, q)
    p = (np.eye(3) - R).dot(np.cross(omega, v)) + np.outer(omega, omega).dot(v) * q
    T = homogeneous_matrix(R, p)
    return T


S = np.array([0, 0, 1, 1, 2, 3])
q = np.pi / 4
T = homogeneous_transformation_from_screw(S, q)
print("Homogeneous transformation matrix from screw axis:\n", T)


Homogeneous transformation matrix from screw axis:
 [[ 0.70710678 -0.70710678  0.          0.12132034]
 [ 0.70710678  0.70710678  0.          1.70710678]
 [ 0.          0.          1.          2.35619449]
 [ 0.          0.          0.          1.        ]]


Screw axis and distance from homogeneous transformation matrix

In [16]:
def screw_from_homogeneous_matrix(T):
    R, p = extract_from_homogeneous_matrix(T)
    omega, theta = rotation_matrix_to_axis_angle(R)
    v = 1/theta*np.dot(np.eye(3) - R, np.cross(omega, p)) + omega * np.dot(omega, p) * theta
    S = np.concatenate((omega, v))
    return S, theta


T = np.array([[1, 0, 0, 1],
              [0, 1, 0, 2],
              [0, 0, 1, 3],
              [0, 0, 0, 1]])
S, q = screw_from_homogeneous_matrix(T)
print("Screw axis S:", S)
print("Distance q:", q)


Screw axis S: [nan nan nan nan nan nan]
Distance q: 0.0


<ipython-input-6-db548ef93552>:3: RuntimeWarning: invalid value encountered in divide
  omega_skew = (R - R.T) / (2 * np.sin(theta))


In [3]:
import numpy as np

def get_screw_axis_and_q(T):


    assert T.shape == (4, 4), "T must be a 4x4 matrix"

    R = T[0:3, 0:3]  # Rotation matrix (3x3)
    d = T[0:3, 3]    # Translation vector (3x1)
    
    # Calculate the angle of rotation from the trace of the rotation matrix
    theta = np.arccos((np.trace(R) - 1) / 2)
    
    # If the angle is close to 0, handle the singular case
    if np.isclose(theta, 0):
        # Pure translation
        s = np.zeros(6)
        s[3:] = d
        q = np.zeros(3)  # Arbitrary point as no rotation
    else:
        # Compute the rotation axis (r)
        r = np.array([
            R[2, 1] - R[1, 2],
            R[0, 2] - R[2, 0],
            R[1, 0] - R[0, 1]
        ]) / (2 * np.sin(theta))
        
        # Calculate the screw axis combining rotation and translation
        v = np.cross(-r, d)
        s = np.hstack([r, v])  # Screw axis (6D vector)
        
        # Compute a point on the screw axis (q)
        q = np.cross(-r, v) / np.dot(r, r)
    
    return s, q

# Example usage:
T = np.array([[0, -1,  0, 1],
              [1,  0,  0, 2],
              [0,  0,  1, 3],
              [0,  0,  0, 1]])

screw_axis, q = get_screw_axis_and_q(T)
print("Screw axis (6D):", screw_axis)
print("Point on the screw axis (q):", q)


Screw axis (6D): [ 0.  0.  1.  2. -1.  0.]
Point on the screw axis (q): [-1. -2.  0.]
